export const menuData = [
  {
    text: 'PROMO PAKET SERVICE',
    subMenu: [
      { text: 'PAKET AC', href: '/paket/ac' },
      { text: 'PAKET COMBO BIASA', href: '/paket/combo-biasa' },
      { text: 'PAKET COMBO SERIES', href: '/paket/combo-series' },
      { text: 'PAKET COMBO ULTRA', href: '/paket/combo-ultra' },
      { text: 'PAKET DETAILING', href: '/paket/detailing' },
      { text: 'PAKET DETAILING VELG', href: '/paket/velg' },
      { text: 'PAKET DIESEL', href: '/paket/diesel' },
      { text: 'PAKET FUEL SYSTEM', href: '/paket/fuel-system' },
      { text: 'PAKET KAKI-KAKI + OLI', href: '/paket/kaki-kaki-oli' },
      { text: 'PAKET NANO CERAMIC', href: '/paket/nano-ceramic' },
      { text: 'PAKET RACKSTEER', href: '/paket/racksteer' },
      { text: 'PAKET REBUILD KAKI-KAKI', href: '/paket/rebuild-kaki-kaki' },
      { text: 'PAKET SHOCKBREAKER', href: '/paket/shockbreaker' },
      { text: 'PAKET SPAREPART KAKI-KAKI', href: '/paket/sparepart-kaki-kaki' },
      { text: 'PAKET STEERING', href: '/paket/steering' },
      { text: 'PAKET TUNE UP 5 IN 1', href: '/paket/tune-up-5-in-1' },
      { text: 'PAKET TEBUS MURAH', href: '/paket/tebus-murah' },
    ],
  },

  { text: 'KEMITRAAN RAJA OTO', href: '/mitra' },
  { text: 'GALLERY', href: '/gallery' },
  { text: 'FAQ', href: '/faq' },
  { text: 'COMPANY PROFILE', href: '/compro' },
  { text: 'TESTIMONI', href: '/testimoni' },
  // { text: 'SOCIAL MEDIA', href: '/social' },
];
